name: Setup Python Cached
description: Configura Python 3.11 con caché de dependencias pip
runs:
  using: "composite"
  steps:
    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install requirements if file exists
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "⚠️ No requirements.txt found. Skipping pip install."
        fi
      shell: bash