# .github/workflows/proof-html.yml
# autor: Kabehz - Jaime Silva
# ultima modificación: 2025-04-23

name: Proof HTML
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: anishathalye/proof-html@v1.1.0
        with:
          directory: ./
